# Generated by Django 2.0.1 on 2018-03-15 22:18

import DimeAPI.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='DimeAPI.City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='DimeAPI.Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='DimeAPI.State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='DimeAPI.ZipCode'),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dimefund',
            name='available_supply',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dimefund',
            name='market_cap',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dimefund',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dimehistory',
            name='time',
            field=models.BigIntegerField(default=0, verbose_name='Close Date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='network',
            name='genesis',
            field=models.IntegerField(default=0, verbose_name='Beginning block Number'),
        ),
        migrations.AlterField(
            model_name='network',
            name='lastBlockChecked',
            field=models.IntegerField(default=0, verbose_name='Url of Network'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='fromUser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='toUser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xchangecurrency',
            name='currency',
            field=models.IntegerField(default=0),
        ),
    ]
