# Generated by Django 2.0.1 on 2018-03-15 22:18

import DimeAPI.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ('id', 'type', 'document', 'user', 'status')},
        ),
        migrations.AlterModelOptions(
            name='useragent',
            options={'ordering': ('platform',)},
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='browser_version',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='device',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='os',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='os_version',
        ),
        migrations.AddField(
            model_name='document',
            name='document',
            field=models.FileField(default=0, upload_to=DimeAPI.models.user_directory_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailserver',
            name='port',
            field=models.IntegerField(default=465),
        ),
        migrations.AddField(
            model_name='useragent',
            name='appName',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True, verbose_name='app Name'),
        ),
        migrations.AddField(
            model_name='useragent',
            name='appVersion',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True, verbose_name='app Version'),
        ),
        migrations.AddField(
            model_name='useragent',
            name='codeName',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True, verbose_name='code Name'),
        ),
        migrations.AddField(
            model_name='useragent',
            name='cookiesEnabled',
            field=models.BooleanField(default=True, verbose_name='cookies'),
        ),
        migrations.AddField(
            model_name='useragent',
            name='inserted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Time inserted'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='useragent',
            name='language',
            field=models.CharField(blank=True, default='Unknown', max_length=30, null=True, verbose_name='language'),
        ),
        migrations.AddField(
            model_name='useragent',
            name='platform',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True, verbose_name='platform'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='DimeAPI.City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='DimeAPI.Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='DimeAPI.State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='DimeAPI.ZipCode'),
        ),
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dimefund',
            name='available_supply',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dimefund',
            name='market_cap',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dimefund',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dimehistory',
            name='time',
            field=models.BigIntegerField(default=0, verbose_name='Close Date'),
        ),
        migrations.AlterField(
            model_name='document',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='network',
            name='genesis',
            field=models.IntegerField(default=0, verbose_name='Beginning block Number'),
        ),
        migrations.AlterField(
            model_name='network',
            name='lastBlockChecked',
            field=models.IntegerField(default=0, verbose_name='Url of Network'),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='fromUser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notification',
            name='toUser',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='xchangecurrency',
            name='currency',
            field=models.IntegerField(default=0),
        ),
    ]
