# Generated by Django 2.0.1 on 2018-01-26 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0002_auto_20180126_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='DimeAPI.NameType'),
        ),
        migrations.AddField(
            model_name='name',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Login'),
        ),
        migrations.AddField(
            model_name='register',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='DimeAPI.RegisterStatus'),
        ),
    ]
