# Generated by Django 2.0.1 on 2018-03-15 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0002_auto_20180315_2218'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='deviceInfo',
            new_name='userAgent',
        ),
    ]
