# Generated by Django 2.0.1 on 2018-01-26 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0003_auto_20180126_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='DimeAPI.UserStatus'),
        ),
    ]
