# Generated by Django 2.0.1 on 2018-01-29 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0005_auto_20180126_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=30)),
                ('symbol', models.CharField(default='', max_length=10)),
                ('coinName', models.CharField(default='', max_length=30)),
                ('fullName', models.CharField(default='', max_length=100)),
                ('totalCoinSupply', models.BigIntegerField(default=0)),
                ('icon', models.CharField(default='default.png', max_length=30)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Dime10Index',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rebalanceDate', models.DateField(default=0)),
                ('rank', models.IntegerField(default=0)),
                ('level', models.FloatField(default=0.0)),
                ('rebalancePrice', models.FloatField(default=0.0)),
                ('marketCap', models.BigIntegerField(default=0)),
                ('percentOfDime', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('rebalanceValue', models.FloatField(default=0.0)),
                ('endPrice', models.FloatField(default=0.0)),
                ('endValue', models.FloatField(default=0.0)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeAPI.Currency')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(default='', max_length=8)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AddField(
            model_name='dime10index',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeAPI.Period'),
        ),
    ]
