# Generated by Django 2.0.1 on 2018-01-29 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0007_auto_20180129_0907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='day',
            new_name='endDay',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='month',
            new_name='endMonth',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='quarter',
            new_name='endQarter',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='year',
            new_name='endYear',
        ),
        migrations.AddField(
            model_name='period',
            name='startDay',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='period',
            name='startMonth',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='period',
            name='startQarter',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='period',
            name='startYear',
            field=models.IntegerField(default=2017),
        ),
    ]
