# Generated by Django 2.0.1 on 2018-01-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0008_auto_20180129_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='totalCoinSupply',
            field=models.FloatField(default=0.0),
        ),
    ]
