# Generated by Django 2.0.1 on 2018-01-30 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0010_auto_20180129_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('email', models.EmailField(default='noemail@thedime.fund', max_length=254, primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ('email',),
            },
        ),
    ]
