# Generated by Django 2.0.1 on 2018-02-05 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0011_newsletter'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAgent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ipAddress', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address of Register')),
                ('userAgent', models.CharField(blank=True, default='Unknown', max_length=200, null=True, verbose_name='User Agent')),
                ('os', models.CharField(blank=True, default='Unknown', max_length=20, null=True, verbose_name='Operating System')),
                ('browser', models.CharField(blank=True, default='Unknown', max_length=20, null=True, verbose_name='Browser')),
                ('device', models.CharField(blank=True, default='Unknown', max_length=20, null=True, verbose_name='Device')),
                ('os_version', models.CharField(blank=True, default='Unknown', max_length=30, null=True, verbose_name='OS Version')),
                ('browser_version', models.CharField(blank=True, default='Unknown', max_length=30, null=True, verbose_name='OS Version')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='DimeAPI.RegisterStatus')),
            ],
        ),
        migrations.AlterField(
            model_name='register',
            name='userAgent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='DimeAPI.UserAgent'),
        ),
    ]
