# Generated by Django 2.0.1 on 2018-02-06 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0012_auto_20180205_1104'),
    ]

    operations = [
        migrations.CreateModel(
            name='Password',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20, verbose_name='Password')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='useragent',
            options={'ordering': ('os',)},
        ),
        migrations.RenameField(
            model_name='register',
            old_name='userAgent',
            new_name='deviceInfo',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='ipAddress',
        ),
        migrations.RemoveField(
            model_name='useragent',
            name='status',
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default='none', max_length=20, verbose_name='Password of Register'),
        ),
        migrations.AlterField(
            model_name='useragent',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
