# Generated by Django 2.0.1 on 2018-02-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0013_auto_20180206_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useragent',
            name='userAgent',
            field=models.CharField(blank=True, default='Unknown', max_length=255, null=True, verbose_name='User Agent'),
        ),
    ]
