# Generated by Django 2.0.1 on 2018-02-08 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0015_auto_20180208_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='inserted',
            field=models.DateTimeField(default=0, verbose_name='Date of Registration'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.UserStatus'),
        ),
    ]
