# Generated by Django 2.0.1 on 2018-02-08 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0016_auto_20180208_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=2, max_length=100, unique=True, verbose_name='username of user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Login of user'),
        ),
    ]
