# Generated by Django 2.0.1 on 2018-02-08 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0017_auto_20180208_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='Username', max_length=100, unique=True, verbose_name='username of user'),
        ),
    ]
