# Generated by Django 2.0.1 on 2018-02-14 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0019_auto_20180208_2304'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimePeriod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.SmallIntegerField(default=0)),
                ('level', models.FloatField(default=0.0)),
                ('rebalancePrice', models.FloatField(default=0.0)),
                ('marketCap', models.BigIntegerField(default=0)),
                ('percentOfDime', models.FloatField(default=0.0)),
                ('amount', models.FloatField(default=0.0)),
                ('rebalanceValue', models.FloatField(default=0.0)),
                ('endPrice', models.FloatField(default=0.0)),
                ('endValue', models.FloatField(default=0.0)),
                ('currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeAPI.Currency')),
                ('period', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeAPI.Period')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('vendor_url', models.CharField(default='', max_length=200)),
                ('api_url', models.CharField(default='', max_length=200)),
                ('api_key', models.CharField(default='', max_length=200)),
                ('api_secret', models.CharField(default='', max_length=200)),
            ],
            options={
                'ordering': ('id', 'name'),
            },
        ),
    ]
