# Generated by Django 2.0.1 on 2018-02-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0020_dimeperiod_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='order',
            field=models.SmallIntegerField(default=1),
        ),
    ]
