# Generated by Django 2.0.1 on 2018-02-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0021_auto_20180214_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='xchange',
            name='api_key',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='xchange',
            name='api_secret',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='xchange',
            name='api_url',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='xchange',
            name='category',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='xchange',
            name='order',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='xchange',
            name='vendor_url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
