# Generated by Django 2.0.1 on 2018-02-14 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0022_auto_20180214_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='api_secret',
            new_name='url',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='order',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='vendor_url',
        ),
        migrations.RemoveField(
            model_name='xchange',
            name='vendor_url',
        ),
        migrations.AddField(
            model_name='vendor',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='api_key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
