# Generated by Django 2.0.1 on 2018-02-14 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0023_auto_20180214_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoCoins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(default='', max_length=200)),
                ('image_url', models.CharField(default='', max_length=200)),
                ('name', models.CharField(default='', max_length=30)),
                ('symbol', models.CharField(default='', max_length=10)),
                ('coin_name', models.CharField(default='', max_length=30)),
                ('full_name', models.CharField(default='', max_length=100)),
                ('min_size', models.FloatField(default=0.0)),
                ('total_coin_supply', models.FloatField(default=0.0)),
                ('proof_type', models.CharField(default='', max_length=20)),
                ('fully_premined', models.SmallIntegerField(default=1)),
                ('algorithm', models.CharField(default='', max_length=10)),
                ('pre_mined_value', models.FloatField(default=0.0)),
                ('sort_order', models.SmallIntegerField(default=1)),
                ('total_coins_free_float', models.CharField(default='', max_length=100)),
                ('sponsored', models.BooleanField(default=False)),
                ('status', models.CharField(default='', max_length=100)),
                ('xchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeAPI.Xchange')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.RemoveField(
            model_name='currency',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='currency',
            name='totalCoinSupply',
        ),
    ]
