# Generated by Django 2.0.1 on 2018-02-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0024_auto_20180214_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocoins',
            name='xchange_coin_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
