# Generated by Django 2.0.1 on 2018-02-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0025_cryptocoins_xchange_coin_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocoins',
            name='xchange_coin_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
