# Generated by Django 2.0.1 on 2018-02-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0026_auto_20180214_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocoins',
            name='algorithm',
            field=models.CharField(default='', max_length=50),
        ),
    ]
