# Generated by Django 2.0.1 on 2018-02-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0027_auto_20180214_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocoins',
            name='pre_mined_value',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='cryptocoins',
            name='total_coins_free_float',
            field=models.CharField(default='', max_length=20),
        ),
    ]
