# Generated by Django 2.0.1 on 2018-02-14 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0029_auto_20180214_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocoins',
            name='coin_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='currency',
            name='coinName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
