# Generated by Django 2.0.1 on 2018-02-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0030_auto_20180214_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocoins',
            name='proof_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
