# Generated by Django 2.0.1 on 2018-02-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0031_auto_20180214_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currencyxchangemap',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='currencyxchangemap',
            name='currencyXChange',
        ),
        migrations.DeleteModel(
            name='CurrencyXchangeMap',
        ),
    ]
