# Generated by Django 2.0.1 on 2018-02-15 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0032_auto_20180215_1047'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CryptoCoins',
            new_name='CryptoCompareCoins',
        ),
    ]
