# Generated by Django 2.0.1 on 2018-02-15 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0033_auto_20180215_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocomparecoins',
            name='min_size',
        ),
        migrations.RemoveField(
            model_name='cryptocomparecoins',
            name='status',
        ),
        migrations.RemoveField(
            model_name='cryptocomparecoins',
            name='xchange_coin_id',
        ),
        migrations.AddField(
            model_name='cryptocomparecoins',
            name='dime_coin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeAPI.Currency'),
        ),
    ]
