# Generated by Django 2.0.1 on 2018-02-15 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0034_auto_20180215_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocomparecoins',
            name='dime_coin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeAPI.Currency'),
        ),
    ]
