# Generated by Django 2.0.1 on 2018-02-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0035_auto_20180215_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocomparecoins',
            name='min_size',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
