# Generated by Django 2.0.1 on 2018-02-15 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0038_auto_20180215_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocomparecoins',
            name='xchange_coin',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
