# Generated by Django 2.0.1 on 2018-02-15 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0039_auto_20180215_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocomparecoins',
            name='id',
        ),
        migrations.AlterField(
            model_name='cryptocomparecoins',
            name='dime_coin',
            field=models.OneToOneField(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to='DimeAPI.Currency'),
        ),
        migrations.AlterField(
            model_name='cryptocomparecoins',
            name='xchange',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeAPI.Xchange'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.AutoField(default=-1, primary_key=True, serialize=False),
        ),
    ]
