# Generated by Django 2.0.1 on 2018-02-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0040_auto_20180215_1140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocomparecoins',
            name='dime_coin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='DimeAPI.Currency'),
        ),
        migrations.AlterField(
            model_name='cryptocomparecoins',
            name='xchange',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.Xchange'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
