# Generated by Django 2.0.1 on 2018-02-15 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0041_auto_20180215_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocomparecoins',
            name='xchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.Xchange'),
        ),
    ]
