# Generated by Django 2.0.1 on 2018-02-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0043_auto_20180215_1228'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CryptoCompareCoins',
            new_name='CryptoCompareCoin',
        ),
    ]
