# Generated by Django 2.0.1 on 2018-02-15 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0044_auto_20180215_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='num_of_coins',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='cryptocomparecoin',
            name='local_coin',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cryptoCompareCoin', serialize=False, to='DimeAPI.Currency'),
        ),
    ]
