# Generated by Django 2.0.1 on 2018-02-15 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0045_auto_20180215_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='endDay',
            new_name='end_day',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='endMonth',
            new_name='end_month',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='endYear',
            new_name='end_year',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='endQarter',
            new_name='start_day',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='startDay',
            new_name='start_month',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='startYear',
            new_name='start_year',
        ),
        migrations.RemoveField(
            model_name='period',
            name='startMonth',
        ),
        migrations.RemoveField(
            model_name='period',
            name='startQarter',
        ),
    ]
