# Generated by Django 2.0.1 on 2018-02-16 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0047_dimemutualfund_available_supply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dimemutualfund',
            name='available_supply',
        ),
    ]
