# Generated by Django 2.0.1 on 2018-02-16 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0048_remove_dimemutualfund_available_supply'),
    ]

    operations = [
        migrations.AddField(
            model_name='dimemutualfund',
            name='available_supply',
            field=models.BigIntegerField(default=0),
        ),
    ]
