# Generated by Django 2.0.1 on 2018-02-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0049_dimemutualfund_available_supply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimeperiod',
            old_name='endPrice',
            new_name='end_price',
        ),
        migrations.RenameField(
            model_name='dimeperiod',
            old_name='endValue',
            new_name='end_value',
        ),
        migrations.RenameField(
            model_name='dimeperiod',
            old_name='marketCap',
            new_name='market_cap',
        ),
        migrations.RenameField(
            model_name='dimeperiod',
            old_name='percentOfDime',
            new_name='percent_of_dime',
        ),
        migrations.RenameField(
            model_name='dimeperiod',
            old_name='rebalancePrice',
            new_name='rebalance_price',
        ),
        migrations.RenameField(
            model_name='dimeperiod',
            old_name='rebalanceValue',
            new_name='rebalance_value',
        ),
        migrations.AlterField(
            model_name='dimemutualfund',
            name='rebalanceDate',
            field=models.DateField(),
        ),
    ]
