# Generated by Django 2.0.1 on 2018-02-16 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0050_auto_20180216_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimemutualfund',
            name='rebalanceDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
