# Generated by Django 2.0.1 on 2018-02-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
       ('DimeAPI', '0050_auto_20180216_1349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimemutualfund',
            old_name='endValue',
            new_name='end_value',
        ),
    ]
