# Generated by Django 2.0.1 on 2018-02-16 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0054_auto_20180216_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimemutualfund',
            old_name='marketCap',
            new_name='market_cap',
        ),
    ]
