# Generated by Django 2.0.1 on 2018-02-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0055_auto_20180216_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimemutualfund',
            old_name='rebalancePrice',
            new_name='rebalance_price',
        ),
    ]
