# Generated by Django 2.0.1 on 2018-02-16 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0057_auto_20180216_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimemutualfund',
            old_name='rebalanceDate',
            new_name='rebalance_date',
        ),
    ]
