# Generated by Django 2.0.1 on 2018-02-19 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0059_ada_bch_btc_btg_currency2_dash_doge_dsh_eos_etc_eth_icn_iota_lsk_ltc_maid_miota_neo_omgc_rep_steem_w'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimeHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.BigIntegerField(default=0, verbose_name='Close Date')),
                ('value', models.FloatField(default=0.0)),
                ('inserted', models.DateTimeField(auto_now_add=True, verbose_name='Time inserted')),
                ('xchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeAPI.Xchange')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
