# Generated by Django 2.0.1 on 2018-02-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0060_dimehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='htmlFilename',
            field=models.FileField(blank=True, null=True, upload_to='DimeAPI/EmailTemplates', verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='textFilename',
            field=models.FileField(blank=True, null=True, upload_to='DimeAPI/EmailTemplates', verbose_name='Filename'),
        ),
    ]
