# Generated by Django 2.0.1 on 2018-02-20 17:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0061_auto_20180219_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('symbol', models.CharField(default='', max_length=10)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='htmlFilename',
            field=models.FileField(blank=True, null=True, upload_to='DimeAPI\\EmailTemplates', verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='textFilename',
            field=models.FileField(blank=True, null=True, upload_to='DimeAPI\\EmailTemplates', verbose_name='Filename'),
        ),
        migrations.AlterField(
            model_name='register',
            name='inserted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date of Registration'),
        ),
        migrations.DeleteModel(
            name='CurrencyHistory',
        ),
    ]
