# Generated by Django 2.0.1 on 2018-02-20 17:31

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0062_auto_20180220_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUsForm',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='noemail@noemail.com', max_length=100, verbose_name='Email')),
                ('subject', models.CharField(max_length=50, verbose_name='Subject of email')),
                ('name', models.CharField(max_length=100, verbose_name='name of person')),
                ('message', models.CharField(max_length=255, verbose_name='message')),
                ('inserted', models.DateTimeField(auto_now_add=True, verbose_name='Date of contact')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DimeHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.BigIntegerField(default=0, verbose_name='Close Date')),
                ('value', models.FloatField(default=0.0)),
                ('inserted', models.DateTimeField(auto_now_add=True, verbose_name='Time inserted')),
                ('xchange', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeAPI.Xchange')),
            ],
            options={
                'ordering': ('id',),
            },
        ),

    ]
