# Generated by Django 2.0.1 on 2018-02-21 15:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0063_auto_20180220_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='zipCode',
            field=models.CharField(default='00000', max_length=10, verbose_name='Zip Code of Register'),
        ),
    ]
