# Generated by Django 2.0.1 on 2018-02-21 15:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0064_auto_20180221_1551'),
    ]

    operations = [

    ]
