# Generated by Django 2.0.1 on 2018-02-21 17:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0065_auto_20180221_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dimemutualfund',
            old_name='endPrice',
            new_name='end_price',
        ),
        migrations.RenameField(
            model_name='dimemutualfund',
            old_name='endValue',
            new_name='end_value',
        ),
        migrations.RenameField(
            model_name='dimemutualfund',
            old_name='marketCap',
            new_name='market_cap',
        ),
        migrations.RenameField(
            model_name='dimemutualfund',
            old_name='percentOfDime',
            new_name='percent_of_dime',
        ),
        migrations.RenameField(
            model_name='dimemutualfund',
            old_name='rebalancePrice',
            new_name='rebalance_price',
        ),
        migrations.RenameField(
            model_name='dimemutualfund',
            old_name='rebalanceValue',
            new_name='rebalance_value',
        ),
        migrations.RemoveField(
            model_name='dimemutualfund',
            name='rebalanceDate',
        ),
        migrations.AddField(
            model_name='dimemutualfund',
            name='rebalance_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
