# Generated by Django 2.0.1 on 2018-03-01 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0067_auto_20180228_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletter',
            name='timestamp2',
            field=models.BigIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='DimePeriod',
        ),
    ]
