# Generated by Django 2.0.1 on 2018-03-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0068_auto_20180301_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='timestamp2',
            new_name='timestamp',
        ),
    ]
