# Generated by Django 2.0.1 on 2018-03-01 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0069_auto_20180301_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(default='noemail@thedime.fund', max_length=100, primary_key=True, serialize=False),
        ),
    ]
