# Generated by Django 2.0.1 on 2018-03-01 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0070_auto_20180301_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='noemail@noemail.com', max_length=100, verbose_name='Email of Affiliate')),
                ('firstName', models.CharField(max_length=50, verbose_name='First Name of Affiliate')),
                ('lastName', models.CharField(max_length=50, verbose_name='Last Name of Affiliate')),
                ('zipCode', models.CharField(default='00000', max_length=10, verbose_name='Zip Code of Affiliate')),
                ('companyName', models.CharField(max_length=50, verbose_name='Company Name of Affiliate')),
                ('inserted', models.DateTimeField(auto_now_add=True, verbose_name='Date of Registration')),
                ('status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='DimeAPI.RegisterStatus')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
