# Generated by Django 2.0.1 on 2018-03-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0071_affiliate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocomparecoin',
            name='local_coin',
        ),
        migrations.RemoveField(
            model_name='cryptocomparecoin',
            name='xchange',
        ),
        migrations.AddField(
            model_name='affiliate',
            name='phoneNumber',
            field=models.CharField(default='0000000000', max_length=20, verbose_name='Phone Number of Affiliate'),
        ),
        migrations.DeleteModel(
            name='CryptoCompareCoin',
        ),
    ]
