# Generated by Django 2.0.1 on 2018-03-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0072_auto_20180303_1442'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimePeriod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('num_of_coins', models.IntegerField(default=10)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
