# Generated by Django 2.0.1 on 2018-03-04 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0073_dimeperiod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dimemutualfund',
            name='period',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='DimeAPI.DimePeriod'),
        ),
    ]
