# Generated by Django 2.0.1 on 2018-03-04 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0074_auto_20180304_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DimeMutualFund',
            new_name='DimeFund',
        ),
    ]
