# Generated by Django 2.0.1 on 2018-03-04 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0075_auto_20180304_0916'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Period',
        ),
    ]
