# Generated by Django 2.0.1 on 2018-03-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0077_auto_20180305_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password',
            name='password',
            field=models.CharField(max_length=64, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='register',
            name='password',
            field=models.CharField(default='none', max_length=64, verbose_name='Password of Register'),
        ),
    ]
