# Generated by Django 2.0.1 on 2018-03-07 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0078_auto_20180305_2215'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Password',
        ),
        migrations.AlterField(
            model_name='emailaddress',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='emails', to=settings.AUTH_USER_MODEL, verbose_name='Login'),
        ),
        migrations.AlterField(
            model_name='name',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='types', to='DimeAPI.NameType', verbose_name='Name Type'),
        ),
        migrations.AlterField(
            model_name='name',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='names', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
