# Generated by Django 2.0.1 on 2018-03-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0079_auto_20180307_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='City Name')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sort_name', models.CharField(default='XX', max_length=3, verbose_name='2 letter name')),
                ('name', models.CharField(default='XXX', max_length=30, verbose_name='City Name')),
                ('phone_code', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('sort_name',),
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, verbose_name='City Name')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.Country')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('zip_code', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('zip_code',),
            },
        ),
        migrations.AlterField(
            model_name='name',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='DimeAPI.NameType', verbose_name='Name Type'),
        ),
        migrations.AddField(
            model_name='state',
            name='zip_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.ZipCode'),
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.State'),
        ),
        migrations.AddField(
            model_name='city',
            name='zip_code',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.ZipCode'),
        ),
    ]
