# Generated by Django 2.0.1 on 2018-03-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0080_auto_20180307_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=40, verbose_name='City Name'),
        ),
    ]
