# Generated by Django 2.0.1 on 2018-03-07 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0081_auto_20180307_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='state',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='city',
            name='zip_codes',
            field=models.ManyToManyField(to='DimeAPI.ZipCode'),
        ),
        migrations.AddField(
            model_name='state',
            name='zip_codes',
            field=models.ManyToManyField(to='DimeAPI.ZipCode'),
        ),
    ]
