# Generated by Django 2.0.1 on 2018-03-07 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0082_auto_20180307_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipcode',
            name='zip_code',
            field=models.CharField(default='00000', max_length=5),
        ),
    ]
