# Generated by Django 2.0.1 on 2018-03-07 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0085_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zipcode',
            options={'ordering': ('zipcode',)},
        ),

        migrations.AlterField(
            model_name='address',
            name='address1',
            field=models.CharField(default='', max_length=255, verbose_name='Address 1'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address2',
            field=models.CharField(default='', max_length=255, verbose_name='Address 2'),
        ),
        migrations.AlterField(
            model_name='address',
            name='address3',
            field=models.CharField(default='', max_length=255, verbose_name='Address 3'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='DimeAPI.City'),
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='DimeAPI.Country'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='DimeAPI.State'),
        ),
        migrations.AlterField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='DimeAPI.ZipCode'),
        ),
    ]
