# Generated by Django 2.0.1 on 2018-03-07 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0086_auto_20180307_1841'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddressType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20, verbose_name='Type of Email Address')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.RenameField(
            model_name='zipcode',
            old_name='zip_code',
            new_name='zipcode',
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.EmailAddressType'),
            preserve_default=False,
        ),
    ]
