# Generated by Django 2.0.1 on 2018-03-07 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0087_auto_20180307_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailaddresstype',
            name='type',
            field=models.CharField(default='0', max_length=20, verbose_name='Type of Email Address'),
        ),
    ]
