# Generated by Django 2.0.1 on 2018-03-08 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0089_auto_20180308_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=16, verbose_name='Phone Number')),
                ('country_code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.Country')),
            ],
            options={
                'ordering': ('id', 'phone_number', 'country_code'),
            },
        ),
        migrations.CreateModel(
            name='PhoneNumberType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20, verbose_name='Type of Phone Number')),
            ],
            options={
                'ordering': ('id', 'type'),
            },
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.PhoneNumberType'),
        ),
    ]
