# Generated by Django 2.0.1 on 2018-03-08 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0090_auto_20180308_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
            ],
        ),
        migrations.RemoveField(
            model_name='address',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='emailaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='name',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='addresses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='userProfile', to='DimeAPI.Address', verbose_name='User Profile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='emailAddresses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='userProfile', to='DimeAPI.EmailAddress', verbose_name='Email Addresses'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='names',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='userProfile', to='DimeAPI.Name', verbose_name='Names'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phoneNumbers',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='userProfile', to='DimeAPI.PhoneNumber', verbose_name='Phone Numbers'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='userProfile', to=settings.AUTH_USER_MODEL, verbose_name='User Profile'),
        ),
    ]
