# Generated by Django 2.0.1 on 2018-03-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0091_auto_20180308_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumbertype',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('id', 'avatar')},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='emailAddresses',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='names',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phoneNumbers',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='address',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='addresses', to='DimeAPI.UserProfile', verbose_name='Addresses'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.UserProfile'),
        ),
        migrations.AddField(
            model_name='emailaddress',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='emailAddresses', to='DimeAPI.UserProfile', verbose_name='User Profile'),
        ),
        migrations.AddField(
            model_name='name',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='names', to='DimeAPI.UserProfile', verbose_name='Names'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='phoneNumbers', to='DimeAPI.UserProfile', verbose_name='Phone Numbers'),
        ),
        migrations.AlterField(
            model_name='phonenumbertype',
            name='type',
            field=models.CharField(default='1', max_length=20, verbose_name='Type of Phone Number'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
