# Generated by Django 2.0.1 on 2018-03-08 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0094_customuser_user_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'ordering': ('id', 'phone_number', 'country')},
        ),
        migrations.RenameField(
            model_name='phonenumber',
            old_name='country_code',
            new_name='country',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_profile',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='customUser', to='DimeAPI.UserProfile'),
        ),
    ]
