# Generated by Django 2.0.1 on 2018-03-08 17:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0095_auto_20180308_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=False),
        ),
    ]
