# Generated by Django 2.0.1 on 2018-03-10 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0100_auto_20180308_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='No Name', max_length=255, verbose_name='Filename of document')),
                ('size', models.IntegerField(default=0)),
                ('inserted', models.DateTimeField(auto_now_add=True, verbose_name='Time inserted')),
                ('modified', models.DateTimeField(auto_now_add=True, verbose_name='Time inserted')),
            ],
            options={
                'ordering': ('id', 'type', 'user', 'status'),
            },
        ),
        migrations.CreateModel(
            name='DocumentStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20, verbose_name='Status of Document')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20, verbose_name='Type of Document')),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20, verbose_name='Type of Document')),
            ],
            options={
                'ordering': ('type',),
            },
        ),
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.FileType'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.DocumentStatus'),
        ),
        migrations.AddField(
            model_name='document',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.DocumentType'),
        ),
        migrations.AddField(
            model_name='document',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DimeAPI.UserProfile'),
        ),
    ]
