# Generated by Django 2.0.1 on 2018-03-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0101_auto_20180310_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(default='No Name', max_length=255, verbose_name='vendor name')),
                ('username', models.CharField(default='No Name', max_length=100, verbose_name='username')),
                ('password', models.CharField(default='No Name', max_length=64, verbose_name='password')),
                ('server', models.CharField(default='No Name', max_length=255, verbose_name='server name')),
            ],
            options={
                'ordering': ('vendor',),
            },
        ),
    ]
