# Generated by Django 2.0.1 on 2018-03-10 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0102_vendors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vendors',
            new_name='MailServer',
        ),
    ]
