# Generated by Django 2.0.1 on 2018-03-14 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DimeAPI', '0103_auto_20180310_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailserver',
            name='port',
            field=models.IntegerField(default=465),
        ),
    ]
